'------------------------------------------------------------------------------
' <auto-generated>
'     Dieser Code wurde von einem Tool generiert.
'     Laufzeitversion:4.0.30319.42000
'
'     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
'     der Code erneut generiert wird.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Namespace My
    
    <Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute(),  _
     Global.System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "16.10.0.0"),  _
     Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
    Partial Friend NotInheritable Class MySettings
        Inherits Global.System.Configuration.ApplicationSettingsBase
        
        Private Shared defaultInstance As MySettings = CType(Global.System.Configuration.ApplicationSettingsBase.Synchronized(New MySettings()),MySettings)
        
#Region "Automatische My.Settings-Speicherfunktion"
#If _MyType = "WindowsForms" Then
    Private Shared addedHandler As Boolean

    Private Shared addedHandlerLockObject As New Object

    <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(), Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)> _
    Private Shared Sub AutoSaveSettings(sender As Global.System.Object, e As Global.System.EventArgs)
        If My.Application.SaveMySettingsOnExit Then
            My.Settings.Save()
        End If
    End Sub
#End If
#End Region
        
        Public Shared ReadOnly Property [Default]() As MySettings
            Get
                
#If _MyType = "WindowsForms" Then
               If Not addedHandler Then
                    SyncLock addedHandlerLockObject
                        If Not addedHandler Then
                            AddHandler My.Application.Shutdown, AddressOf AutoSaveSettings
                            addedHandler = True
                        End If
                    End SyncLock
                End If
#End If
                Return defaultInstance
            End Get
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("True")>  _
        Public Property firstRun() As Boolean
            Get
                Return CType(Me("firstRun"),Boolean)
            End Get
            Set
                Me("firstRun") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("board_manager:"&Global.Microsoft.VisualBasic.ChrW(13)&Global.Microsoft.VisualBasic.ChrW(10)&"  additional_urls:"&Global.Microsoft.VisualBasic.ChrW(13)&Global.Microsoft.VisualBasic.ChrW(10)&"    - https://arduino.esp8266.com/stable/pack"& _ 
            "age_esp8266com_index.json")>  _
        Public Property append() As String
            Get
                Return CType(Me("append"),String)
            End Get
            Set
                Me("append") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("Ly8tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0KI2luY2x1ZGUgPEVTUDgyNjZXaUZpLmg+ICAKI"& _ 
            "2luY2x1ZGUgPEVTUDgyNjZIVFRQQ2xpZW50Lmg+CiNpbmNsdWRlIDxXaUZpQ2xpZW50Lmg+CiNpbmNsd"& _ 
            "WRlIDxBcmR1aW5vX0pTT04uaD4KI2luY2x1ZGUgIkRIVC5oIgojaW5jbHVkZSA8QXJkdWlub0pzb24ua"& _ 
            "D4KLy8tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0KZmxvYXQgVmVyc2lvbiA9IDEuMzsKLy8tL"& _ 
            "S0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0KU3RyaW5nIHNzaWRfc2V0dXAgICAgID0gIiVTU0lEJ"& _ 
            "SI7ClN0cmluZyBwYXNzd29yZF9zZXR1cCA9ICIlU1NJRFBBU1NXT1JEJSI7ClN0cmluZyBzZWNyZXRrZ"& _ 
            "XkgICAgICA9ICIlU0VDUkVUS0VZJSI7ClN0cmluZyBiYWNrZW5kICAgICAgICA9ICJodHRwOi8vJUJBQ"& _ 
            "0tFTkQlOjgwODAiOwpTdHJpbmcgZXNwbmFtZSAgICAgICAgPSAiJUVTUE5BTUUlIjsKLy8tLS0tLS0tL"& _ 
            "S0tLS0tLS0tLS0tLS0tLS0tLS0tLS0KI2RlZmluZSBESFRUWVBFIERIVDExCi8vIERIVCBTZW5zb3IKd"& _ 
            "WludDhfdCBESFRQaW4gPSAxMjsgLy8xNCBiZXZvciBMw7Z0dGVzdApKU09OVmFyIGRhdGE7CmZsb2F0I"& _ 
            "GRodEh1bWlkaXR5ID0gMDsKZmxvYXQgZGh0VGVtcGVyYXR1cmUgPSAwOyAgIApTdHJpbmcgbG9jYWxpc"& _ 
            "DsgICAgICAgICAgIAovLyBJbml0aWFsaXplIERIVCBzZW5zb3IuCkRIVCBkaHQoREhUUGluLCBESFRUW"& _ 
            "VBFKTsgICAKaW50IG5ldHdvcms7ClN0cmluZyBtZXNzYWdlID0gIiI7CmZsb2F0IHRlbXA7CmZsb2F0I"& _ 
            "Gh1bWlkOwpEeW5hbWljSnNvbkRvY3VtZW50IGRhdGFzZW5kKDEwMjQpOwoKdm9pZCBzZXR1cCgpIHsKI"& _ 
            "CBTZXJpYWwuYmVnaW4oMTE1MjAwKTsKICBwaW5Nb2RlKERIVFBpbiwgSU5QVVQpOwogIGRodC5iZWdpb"& _ 
            "igpOwoKCiAgV2lGaS5iZWdpbihzc2lkX3NldHVwLCBwYXNzd29yZF9zZXR1cCk7ICAgICAgICAgICAgI"& _ 
            "C8vIENvbm5lY3QgdG8gdGhlIG5ldHdvcmsKICBTZXJpYWwucHJpbnQoIkNvbm5lY3RpbmcgdG8gIik7C"& _ 
            "iAgU2VyaWFsLnByaW50KHNzaWRfc2V0dXApOyBTZXJpYWwucHJpbnRsbigiIC4uLiIpOwogIAogIGlud"& _ 
            "CBpID0gMDsKICB3aGlsZSAoV2lGaS5zdGF0dXMoKSAhPSBXTF9DT05ORUNURUQpIHsgLy8gV2FpdCBmb"& _ 
            "3IgdGhlIFdpLUZpIHRvIGNvbm5lY3QKICAgIGRlbGF5KDEwMDApOwogICAgU2VyaWFsLnByaW50KCsra"& _ 
            "Sk7IFNlcmlhbC5wcmludCgnICcpOwogIH0KICAKICBTZXJpYWwucHJpbnRsbignXG4nKTsKICBTZXJpY"& _ 
            "WwucHJpbnRsbigiQ29ubmVjdGlvbiBlc3RhYmxpc2hlZCEiKTsgIAogIFNlcmlhbC5wcmludCgiSVAgY"& _ 
            "WRkcmVzczpcdCIpOwogIFNlcmlhbC5wcmludGxuKFdpRmkubG9jYWxJUCgpKTsKICAKICAKICBTZXJpY"& _ 
            "WwucHJpbnQoIiMjIyNSZWdpc3RlciBEZXZpY2UjIyMjIyIpOyAgCiAgZGF0YXNlbmRbIm5hbWUiXSA9I"& _ 
            "GVzcG5hbWU7CiAgZGF0YXNlbmRbInNlY3JldGtleSJdID0gc2VjcmV0a2V5OwogIGRhdGFzZW5kWyJ0Z"& _ 
            "W1wZXJhdHVyZSJdID0gdGVtcDsKICBkYXRhc2VuZFsiaHVtaWRpdHkiXSA9IGh1bWlkOwogIGRhdGFzZ"& _ 
            "W5kWyJ2ZXJzaW9uIl0gPSAiMS4zIjsKICBkYXRhc2VuZFsibW9kZWwiXSA9ICJUaGVybW9zdGF0IjsKI"& _ 
            "CBkYXRhc2VuZFsiaXBhZGRyZXNzIl0gPSBXaUZpLmxvY2FsSVAoKS50b1N0cmluZygpOwogIFNlcmlhb"& _ 
            "C5wcmludGxuKCJOYW1lOiAiICsgZXNwbmFtZSk7CiAgU2VyaWFsLnByaW50bG4oIlNlY3JldGtleTogI"& _ 
            "iArIFN0cmluZyhkYXRhc2VuZFsic2VjcmV0a2V5Il0pKTsKICBTZXJpYWwucHJpbnRsbigiVmVyc2lvb"& _ 
            "jogIiArIFN0cmluZyhkYXRhc2VuZFsidmVyc2lvbiJdKSk7CiAgU2VyaWFsLnByaW50bG4oIklQQWRkc"& _ 
            "mVzczogIiArIFN0cmluZyhkYXRhc2VuZFsiaXBhZGRyZXNzIl0pKTsKICBTZXJpYWwucHJpbnRsbigiV"& _ 
            "GVtcDogIiArIFN0cmluZyh0ZW1wKSArICIgSHVtaWRpdHk6ICIgKyBTdHJpbmcoaHVtaWQpKTsKICBTd"& _ 
            "HJpbmcgZGF0YXNlbmR4OwogIHNlcmlhbGl6ZUpzb24oZGF0YXNlbmQsIGRhdGFzZW5keCk7CiAgCiAgU"& _ 
            "2VyaWFsLnByaW50KCIjIyMjIyMjIyMjIyMjIyMjIyMjIyMjIyMjIyMjIyMiKTsgIAogIFdpRmlDbGllb"& _ 
            "nQgY2xpZW50OwogIEhUVFBDbGllbnQgaHR0cDsKICBodHRwLmJlZ2luKGNsaWVudCwgYmFja2VuZCArI"& _ 
            "CIvY2xpZW50L3JlZ2lzdGVyLyIpOwogIGh0dHAuYWRkSGVhZGVyKCJDb250ZW50LVR5cGUiLCAiYXBwb"& _ 
            "GljYXRpb24vanNvbiIpOwogIGludCBodHRwUG9zdFJlc3BvbnNlID0gaHR0cC5QT1NUKGRhdGFzZW5ke"& _ 
            "Ck7ICAKICBodHRwLmVuZCgpOwoKICB1cGRhdGVEYXRhKCk7Cn0KCnZvaWQgbG9vcCgpIHsKICAKfQoKd"& _ 
            "m9pZCB1cGRhdGVEYXRhKCl7ICAgICAKICB3aGlsZSAodHJ1ZSkgewogICAgZm9yIChpbnQgaSA9IDA7I"& _ 
            "GkgPD0gMTA7IGkrKykgewogICAgICBkaHRIdW1pZGl0eSA9IGRodC5yZWFkSHVtaWRpdHkoKTsKICAgI"& _ 
            "CAgZGh0VGVtcGVyYXR1cmUgPSBkaHQucmVhZFRlbXBlcmF0dXJlKCk7CiAgICAgIGRlbGF5KDEwMCk7C"& _ 
            "iAgICAgIHRlbXAgPSBkaHRUZW1wZXJhdHVyZTsKICAgICAgaHVtaWQgPSBkaHRIdW1pZGl0eTsKICAgI"& _ 
            "H0KICAgIAoKICAgIGRhdGFzZW5kWyJuYW1lIl0gPSBlc3BuYW1lOwogICAgZGF0YXNlbmRbInNlY3Jld"& _ 
            "GtleSJdID0gc2VjcmV0a2V5OwogICAgZGF0YXNlbmRbInRlbXBlcmF0dXJlIl0gPSB0ZW1wOwogICAgZ"& _ 
            "GF0YXNlbmRbImh1bWlkaXR5Il0gPSBodW1pZDsKICAgIGRhdGFzZW5kWyJ2ZXJzaW9uIl0gPSAiMS4zI"& _ 
            "jsKICAgIGRhdGFzZW5kWyJtb2RlbCJdID0gIlRoZXJtb3N0YXQiOwogICAgZGF0YXNlbmRbImlwYWRkc"& _ 
            "mVzcyJdID0gV2lGaS5sb2NhbElQKCkudG9TdHJpbmcoKTsKICAgIFNlcmlhbC5wcmludCgiIyMjI1VQR"& _ 
            "EFURSBERVZJQ0UjIyMjIyIpOyAgCiAgICBTZXJpYWwucHJpbnRsbigiTmFtZTogIiArIGVzcG5hbWUpO"& _ 
            "wogICAgU2VyaWFsLnByaW50bG4oIlNlY3JldGtleTogIiArIFN0cmluZyhkYXRhc2VuZFsic2VjcmV0a"& _ 
            "2V5Il0pKTsKICAgIFNlcmlhbC5wcmludGxuKCJWZXJzaW9uOiAiICsgU3RyaW5nKGRhdGFzZW5kWyJ2Z"& _ 
            "XJzaW9uIl0pKTsKICAgIFNlcmlhbC5wcmludGxuKCJJUEFkZHJlc3M6ICIgKyBTdHJpbmcoZGF0YXNlb"& _ 
            "mRbImlwYWRkcmVzcyJdKSk7CiAgICBTZXJpYWwucHJpbnRsbigiVGVtcDogIiArIFN0cmluZyh0ZW1wK"& _ 
            "SArICIgSHVtaWRpdHk6ICIgKyBTdHJpbmcoaHVtaWQpKTsKICAgIGxvY2FsaXAgPSBXaUZpLmxvY2FsS"& _ 
            "VAoKS50b1N0cmluZygpOwogICAgU2VyaWFsLnByaW50bG4oIkxvY2FsIElQIGZyb20gVkFSOiAiICsgb"& _ 
            "G9jYWxpcCk7CgogICAgU3RyaW5nIGRhdGFzZW5keDsKICAgIHNlcmlhbGl6ZUpzb24oZGF0YXNlbmQsI"& _ 
            "GRhdGFzZW5keCk7CiAgICAvL1NlcmlhbC5wcmludGxuKCJTZW5kaW5nIERhdGE6ICIgKyBKU09OLnN0c"& _ 
            "mluZ2lmeShkYXRhKSArICIgdG8gLT4gIiArIGRhdGF4WyJiYWNrZW5kIl0gKyAiL2NsaWVudC9yZWdpc"& _ 
            "3Rlci8iKTsKICAgIAogICAgU2VyaWFsLnByaW50KCJVcGRhdGluZyBEYXRhc2V0Olx0Iik7ICAKICAgI"& _ 
            "FdpRmlDbGllbnQgY2xpZW50OwogICAgSFRUUENsaWVudCBodHRwOwogICAgaHR0cC5iZWdpbihjbGllb"& _ 
            "nQsIGJhY2tlbmQgKyAiL2NsaWVudC91cGRhdGUvIik7CiAgICBodHRwLmFkZEhlYWRlcigiQ29udGVud"& _ 
            "C1UeXBlIiwgImFwcGxpY2F0aW9uL2pzb24iKTsKICAgIGludCBodHRwUG9zdFJlc3BvbnNlID0gaHR0c"& _ 
            "C5QT1NUKGRhdGFzZW5keCk7ICAKICAgIGh0dHAuZW5kKCk7CiAgICBTZXJpYWwucHJpbnRsbigpOwogI"& _ 
            "CAgZGVsYXkoNjAwMDApOyAvLzNlOCBmw7xyIDVtaW4KICB9Cn0=")>  _
        Public Property srcThermy_bak() As String
            Get
                Return CType(Me("srcThermy_bak"),String)
            End Get
            Set
                Me("srcThermy_bak") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("daemon:"&Global.Microsoft.VisualBasic.ChrW(13)&Global.Microsoft.VisualBasic.ChrW(10)&"  port: ""50051"""&Global.Microsoft.VisualBasic.ChrW(13)&Global.Microsoft.VisualBasic.ChrW(10)&"directories:"&Global.Microsoft.VisualBasic.ChrW(13)&Global.Microsoft.VisualBasic.ChrW(10)&"  data: %CFGPATH%"&Global.Microsoft.VisualBasic.ChrW(13)&Global.Microsoft.VisualBasic.ChrW(10)&"  downloads: %CFGPATH%"& _ 
            "\staging"&Global.Microsoft.VisualBasic.ChrW(13)&Global.Microsoft.VisualBasic.ChrW(10)&"library:"&Global.Microsoft.VisualBasic.ChrW(13)&Global.Microsoft.VisualBasic.ChrW(10)&"  enable_unsafe_install: false"&Global.Microsoft.VisualBasic.ChrW(13)&Global.Microsoft.VisualBasic.ChrW(10)&"logging:"&Global.Microsoft.VisualBasic.ChrW(13)&Global.Microsoft.VisualBasic.ChrW(10)&"  file: """""&Global.Microsoft.VisualBasic.ChrW(13)&Global.Microsoft.VisualBasic.ChrW(10)&"  form"& _ 
            "at: text"&Global.Microsoft.VisualBasic.ChrW(13)&Global.Microsoft.VisualBasic.ChrW(10)&"  level: info"&Global.Microsoft.VisualBasic.ChrW(13)&Global.Microsoft.VisualBasic.ChrW(10)&"metrics:"&Global.Microsoft.VisualBasic.ChrW(13)&Global.Microsoft.VisualBasic.ChrW(10)&"  addr: :9090"&Global.Microsoft.VisualBasic.ChrW(13)&Global.Microsoft.VisualBasic.ChrW(10)&"  enabled: true"&Global.Microsoft.VisualBasic.ChrW(13)&Global.Microsoft.VisualBasic.ChrW(10)&"output:"&Global.Microsoft.VisualBasic.ChrW(13)&Global.Microsoft.VisualBasic.ChrW(10)&"  no"& _ 
            "_color: false"&Global.Microsoft.VisualBasic.ChrW(13)&Global.Microsoft.VisualBasic.ChrW(10)&"sketch:"&Global.Microsoft.VisualBasic.ChrW(13)&Global.Microsoft.VisualBasic.ChrW(10)&"  always_export_binaries: false"&Global.Microsoft.VisualBasic.ChrW(13)&Global.Microsoft.VisualBasic.ChrW(10)&"updater:"&Global.Microsoft.VisualBasic.ChrW(13)&Global.Microsoft.VisualBasic.ChrW(10)&"  enable_noti"& _ 
            "fication: true"&Global.Microsoft.VisualBasic.ChrW(13)&Global.Microsoft.VisualBasic.ChrW(10)&"board_manager:"&Global.Microsoft.VisualBasic.ChrW(13)&Global.Microsoft.VisualBasic.ChrW(10)&"  additional_urls:"&Global.Microsoft.VisualBasic.ChrW(13)&Global.Microsoft.VisualBasic.ChrW(10)&"    - https://arduino.esp826"& _ 
            "6.com/stable/package_esp8266com_index.json"&Global.Microsoft.VisualBasic.ChrW(13)&Global.Microsoft.VisualBasic.ChrW(10))>  _
        Public Property cfgFile() As String
            Get
                Return CType(Me("cfgFile"),String)
            End Get
            Set
                Me("cfgFile") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("Ly8tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0KI2luY2x1ZGUgPEVTUDgyNjZXaUZpLmg+CiNpb"& _ 
            "mNsdWRlIDxFU1A4MjY2SFRUUENsaWVudC5oPgojaW5jbHVkZSA8V2lGaUNsaWVudC5oPgojaW5jbHVkZ"& _ 
            "SA8QXJkdWlub19KU09OLmg+CiNpbmNsdWRlIDxBcmR1aW5vSnNvbi5oPgovLy0tLS0tLS0tLS1WZXJza"& _ 
            "W9uLS0tLS0tLS0tLS0tLQpTdHJpbmcgVmVyc2lvbiA9ICIwLjIiOwovLy0tLS0tLS0tLS0tLS0tLS0tL"& _ 
            "S0tLS0tLS0tLS0tLQovLy0tLS0tLS0tLS0tU2V0dXAtLS0tLS0tLS0tLS0tLQpTdHJpbmcgc3NpZF9zZ"& _ 
            "XR1cCAgICAgPSAiJVNTSUQlIjsKU3RyaW5nIHBhc3N3b3JkX3NldHVwID0gIiVTU0lEUEFTU1dPUkQlI"& _ 
            "jsKU3RyaW5nIHNlY3JldGtleSAgICAgID0gIiVTRUNSRVRLRVklIjsKU3RyaW5nIGJhY2tlbmQgICAgI"& _ 
            "CAgID0gImh0dHA6Ly8lQkFDS0VORCU6ODA4MCI7ClN0cmluZyBlc3BuYW1lICAgICAgICA9ICIlRVNQT"& _ 
            "kFNRSUiOwovLy0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLQovLy0tLS0tLS0tLS0tLVZhcnMtL"& _ 
            "S0tLS0tLS0tLS0tLQpjb25zdCBpbnQgUElSU2Vuc29yT3V0UGluID0gMTM7ICAgIC8vUElSIFNlbnNvc"& _ 
            "iBPVVQgUGluCmludCBsYXN0U3RhdGU7ClN0cmluZyBhcm1lZDsKU3RyaW5nIG1lc3NhZ2UgPSAiIjsKa"& _ 
            "W50IGlucHV0UGluID0gMTM7ICAgICAgICAgICAgICAgLy8gY2hvb3NlIHRoZSBpbnB1dCBwaW4gKGZvc"& _ 
            "iBQSVIgc2Vuc29yKQppbnQgcGlyU3RhdGUgPSBMT1c7ICAgICAgICAgICAgIC8vIHdlIHN0YXJ0LCBhc"& _ 
            "3N1bWluZyBubyBtb3Rpb24gZGV0ZWN0ZWQKaW50IHZhbCA9IDA7ICAgICAgICAgICAgICAgICAgICAvL"& _ 
            "yB2YXJpYWJsZSBmb3IgcmVhZGluZyB0aGUgcGluIHN0YXR1cwpXaUZpQ2xpZW50IGNsaWVudDsKSFRUU"& _ 
            "ENsaWVudCBodHRwOwpEeW5hbWljSnNvbkRvY3VtZW50IGRhdGFzZW5kKDEwMjQpOwoKCnZvaWQgc2V0d"& _ 
            "XAoKSB7CiAgU2VyaWFsLmJlZ2luKDExNTIwMCk7CiAgV2lGaS5iZWdpbihzc2lkX3NldHVwLCBwYXNzd"& _ 
            "29yZF9zZXR1cCk7ICAgICAgICAgICAgIC8vIENvbm5lY3QgdG8gdGhlIG5ldHdvcmsKICBTZXJpYWwuc"& _ 
            "HJpbnQoIkNvbm5lY3RpbmcgdG8gIik7CiAgU2VyaWFsLnByaW50KHNzaWRfc2V0dXApOyBTZXJpYWwuc"& _ 
            "HJpbnRsbigiIC4uLiIpOwogIGludCBpID0gMDsKICB3aGlsZSAoV2lGaS5zdGF0dXMoKSAhPSBXTF9DT"& _ 
            "05ORUNURUQpIHsgLy8gV2FpdCBmb3IgdGhlIFdpLUZpIHRvIGNvbm5lY3QKICAgIGRlbGF5KDEwMDApO"& _ 
            "wogICAgU2VyaWFsLnByaW50KCsraSk7IFNlcmlhbC5wcmludCgnICcpOwogIH0KCiAgU2VyaWFsLnBya"& _ 
            "W50bG4oJ1xuJyk7CiAgU2VyaWFsLnByaW50bG4oIkNvbm5lY3Rpb24gZXN0YWJsaXNoZWQhIik7CiAgU"& _ 
            "2VyaWFsLnByaW50KCJJUCBhZGRyZXNzOlx0Iik7CiAgU2VyaWFsLnByaW50bG4oV2lGaS5sb2NhbElQK"& _ 
            "CkpOwogIHBpbk1vZGUoUElSU2Vuc29yT3V0UGluLCBJTlBVVCk7CiAgbGFzdFN0YXRlID0gZGlnaXRhb"& _ 
            "FJlYWQoUElSU2Vuc29yT3V0UGluKTsKICByZWdpc3RlckRldmljZSgpOwp9Cgp2b2lkIHJlZ2lzdGVyR"& _ 
            "GV2aWNlKCkgewogIFNlcmlhbC5wcmludCgiIyMjI1JlZ2lzdGVyIERldmljZSMjIyMjIik7CiAgZGF0Y"& _ 
            "XNlbmRbIm5hbWUiXSA9IGVzcG5hbWU7CiAgZGF0YXNlbmRbInNlY3JldGtleSJdID0gc2VjcmV0a2V5O"& _ 
            "wogIGRhdGFzZW5kWyJ2ZXJzaW9uIl0gPSBWZXJzaW9uOwogIGRhdGFzZW5kWyJtb2RlbCJdID0gIk1vd"& _ 
            "GlvbnNlbnNvciI7CiAgU2VyaWFsLnByaW50bG4oIk5hbWU6ICIgKyBlc3BuYW1lKTsKICBTZXJpYWwuc"& _ 
            "HJpbnRsbigiU2VjcmV0a2V5OiAiICsgU3RyaW5nKGRhdGFzZW5kWyJzZWNyZXRrZXkiXSkpOwogIFNlc"& _ 
            "mlhbC5wcmludGxuKCJWZXJzaW9uOiAiICsgU3RyaW5nKGRhdGFzZW5kWyJ2ZXJzaW9uIl0pKTsKICBTd"& _ 
            "HJpbmcgZGF0YXNlbmR4OwogIHNlcmlhbGl6ZUpzb24oZGF0YXNlbmQsIGRhdGFzZW5keCk7CgogIFNlc"& _ 
            "mlhbC5wcmludCgiIyMjIyMjIyMjIyMjIyMjIyMjIyMjIyMjIyMjIyMjIik7CiAgaHR0cC5iZWdpbihjb"& _ 
            "GllbnQsIGJhY2tlbmQgKyAiL2NsaWVudC9yZWdpc3Rlci8iKTsKICBodHRwLmFkZEhlYWRlcigiQ29ud"& _ 
            "GVudC1UeXBlIiwgImFwcGxpY2F0aW9uL2pzb24iKTsKICBpbnQgaHR0cFBvc3RSZXNwb25zZSA9IGh0d"& _ 
            "HAuUE9TVChkYXRhc2VuZHgpOwogIGh0dHAuZW5kKCk7Cn0KCmJvb2wgaXNTeXN0ZW1Bcm1lZCgpIHsKI"& _ 
            "CBodHRwLmJlZ2luKGNsaWVudCwgYmFja2VuZCArICIvYWxhcm0vbW90aW9uL2NoZWNrLyIgKyBlc3BuY"& _ 
            "W1lKTsgICAgIC8vU3BlY2lmeSByZXF1ZXN0IGRlc3RpbmF0aW9uCiAgaW50IGh0dHBDb2RlID0gaHR0c"& _ 
            "C5HRVQoKTsgICAgICAgICAgICAvL1NlbmQgdGhlIHJlcXVlc3QKICBTdHJpbmcgcGF5bG9hZCA9IGh0d"& _ 
            "HAuZ2V0U3RyaW5nKCk7ICAgIC8vR2V0IHRoZSByZXNwb25zZSBwYXlsb2FkIGZyb20gc2VydmVyCiAgU"& _ 
            "2VyaWFsLnByaW50bG4ocGF5bG9hZCk7ICAgIC8vUHJpbnQgcmVxdWVzdCByZXNwb25zZSBwYXlsb2FkC"& _ 
            "iAgaWYgKGh0dHBDb2RlID09IDIwMCkgewogICAgYXJtZWQgPSBwYXlsb2FkOwogICAgaWYgKHBheWxvY"& _ 
            "WQgPT0gImFybWVkIikgewogICAgICByZXR1cm4gdHJ1ZTsKICAgIH0gZWxzZSB7CiAgICAgIHJldHVyb"& _ 
            "iBmYWxzZTsKICAgIH0KICB9IGVsc2UgewogICAgU2VyaWFsLnByaW50bG4oIkVycm9yIGNoZWNraW5nI"& _ 
            "GFybWluZyBzdGF0dXMhIik7CiAgfQogIGh0dHAuZW5kKCk7ICAvL0Nsb3NlIGNvbm5lY3Rpb24KfQoKd"& _ 
            "m9pZCB0cmlnZ2VyQWxhcm0oYm9vbCBtb3Rpb24pIHsKCiAgaWYgKG1vdGlvbiA9PSB0cnVlKSB7CiAgI"& _ 
            "CBodHRwLmJlZ2luKGNsaWVudCwgYmFja2VuZCArICIvYWxhcm0vbW90aW9uL3RyaWdnZXIvIiArIGVzc"& _ 
            "G5hbWUpOyAgICAgLy9TcGVjaWZ5IHJlcXVlc3QgZGVzdGluYXRpb24KICAgIGludCBodHRwQ29kZSA9I"& _ 
            "Gh0dHAuR0VUKCk7ICAgICAgICAgICAgLy9TZW5kIHRoZSByZXF1ZXN0CiAgICBTdHJpbmcgcGF5bG9hZ"& _ 
            "CA9IGh0dHAuZ2V0U3RyaW5nKCk7ICAgIC8vR2V0IHRoZSByZXNwb25zZSBwYXlsb2FkIGZyb20gc2Vyd"& _ 
            "mVyCiAgICBTZXJpYWwucHJpbnRsbigiTW90aW9uIEFsZXJ0IHRyaWdnZXJlZCEiKTsgICAgLy9Qcmlud"& _ 
            "CByZXF1ZXN0IHJlc3BvbnNlIHBheWxvYWQKICAgIGh0dHAuZW5kKCk7ICAvL0Nsb3NlIGNvbm5lY3Rpb"& _ 
            "24KICB9IGVsc2UgewogICAgaHR0cC5iZWdpbihjbGllbnQsIGJhY2tlbmQgKyAiL2FsYXJtL21vdGlvb"& _ 
            "i9kaXNhcm0vIiArIGVzcG5hbWUpOyAgICAgLy9TcGVjaWZ5IHJlcXVlc3QgZGVzdGluYXRpb24KICAgI"& _ 
            "GludCBodHRwQ29kZSA9IGh0dHAuR0VUKCk7ICAgICAgICAgICAgLy9TZW5kIHRoZSByZXF1ZXN0CiAgI"& _ 
            "CBTdHJpbmcgcGF5bG9hZCA9IGh0dHAuZ2V0U3RyaW5nKCk7ICAgIC8vR2V0IHRoZSByZXNwb25zZSBwY"& _ 
            "Xlsb2FkIGZyb20gc2VydmVyCiAgICBTZXJpYWwucHJpbnRsbigiRGlzYXJtZWQiKTsgICAgLy9Qcmlud"& _ 
            "CByZXF1ZXN0IHJlc3BvbnNlIHBheWxvYWQKICAgIGh0dHAuZW5kKCk7ICAvL0Nsb3NlIGNvbm5lY3Rpb"& _ 
            "24KICB9Cn0KCgp2b2lkIGxvb3AoKSB7CiAgaW50IFNlbnNvckRhdGE7CiAgU2Vuc29yRGF0YSA9IGRpZ"& _ 
            "2l0YWxSZWFkKFBJUlNlbnNvck91dFBpbik7CiAgaWYgKCFsYXN0U3RhdGUgPT0gU2Vuc29yRGF0YSkge"& _ 
            "wogICAgU2VyaWFsLnByaW50bG4oIiBTdGF0ZSBDaGFuZ2VkIHRvOiAiICsgU2Vuc29yRGF0YSk7CiAgI"& _ 
            "CBsYXN0U3RhdGUgPSBTZW5zb3JEYXRhOwogICAgaWYgKFNlbnNvckRhdGEgPT0gSElHSCkgewogICAgI"& _ 
            "CBTZXJpYWwucHJpbnRsbigiUGVyc29uIGRldGVjdGVkIik7CiAgICAgIGlmIChpc1N5c3RlbUFybWVkK"& _ 
            "SB7CiAgICAgICAgdHJpZ2dlckFsYXJtKHRydWUpOwogICAgICB9CiAgICB9IGVsc2UgewogICAgICB0c"& _ 
            "mlnZ2VyQWxhcm0oZmFsc2UpOwogICAgICBTZXJpYWwucHJpbnRsbigiTm8gcGVyc29uIGRldGVjdGVkL"& _ 
            "2Rpc2FybWVkIik7CiAgICB9CiAgfQogIGRhdGFzZW5kWyJuYW1lIl0gPSBlc3BuYW1lOwogIGRhdGFzZ"& _ 
            "W5kWyJzZWNyZXRrZXkiXSA9IHNlY3JldGtleTsKICBkYXRhc2VuZFsidmVyc2lvbiJdID0gVmVyc2lvb"& _ 
            "jsKICBkYXRhc2VuZFsibW9kZWwiXSA9ICJNb3Rpb25zZW5zb3IiOwogIFNlcmlhbC5wcmludGxuKCIjI"& _ 
            "yMjVVBEQVRFIERFVklDRSMjIyMjIik7CiAgU2VyaWFsLnByaW50bG4oIk5hbWU6ICIgKyBlc3BuYW1lK"& _ 
            "TsKICBTZXJpYWwucHJpbnRsbigiU2VjcmV0a2V5OiAiICsgU3RyaW5nKGRhdGFzZW5kWyJzZWNyZXRrZ"& _ 
            "XkiXSkpOwogIFNlcmlhbC5wcmludGxuKCJWZXJzaW9uOiAiICsgU3RyaW5nKGRhdGFzZW5kWyJ2ZXJza"& _ 
            "W9uIl0pKTsKICBTZXJpYWwucHJpbnRsbigiU2Vuc29yIFN0YXR1czogIiArIFN0cmluZyhsYXN0U3Rhd"& _ 
            "GUpKTsKICBTZXJpYWwucHJpbnRsbigiIyMjIyMjIyMjIyMjIyMjIyMjIyMjIyIpOwogIFN0cmluZyBkY"& _ 
            "XRhc2VuZHg7CiAgc2VyaWFsaXplSnNvbihkYXRhc2VuZCwgZGF0YXNlbmR4KTsKICBodHRwLmJlZ2luK"& _ 
            "GNsaWVudCwgYmFja2VuZCArICIvY2xpZW50L3VwZGF0ZSIpOwogIGh0dHAuYWRkSGVhZGVyKCJDb250Z"& _ 
            "W50LVR5cGUiLCAiYXBwbGljYXRpb24vanNvbiIpOwogIGludCBodHRwUG9zdFJlc3BvbnNlID0gaHR0c"& _ 
            "C5QT1NUKGRhdGFzZW5keCk7CiAgaHR0cC5lbmQoKTsKICBkZWxheSgxMDAwMCk7Cn0=")>  _
        Public Property srcMotion() As String
            Get
                Return CType(Me("srcMotion"),String)
            End Get
            Set
                Me("srcMotion") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("Ly8tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0KI2luY2x1ZGUgPEVTUDgyNjZXaUZpLmg+ICAKI"& _ 
            "2luY2x1ZGUgPEVTUDgyNjZIVFRQQ2xpZW50Lmg+CiNpbmNsdWRlIDxXaUZpQ2xpZW50Lmg+CiNpbmNsd"& _ 
            "WRlIDxBcmR1aW5vX0pTT04uaD4KI2luY2x1ZGUgIkRIVC5oIgojaW5jbHVkZSA8QXJkdWlub0pzb24ua"& _ 
            "D4KLy8gRm9yIGEgY29ubmVjdGlvbiB2aWEgSTJDIHVzaW5nIHRoZSBBcmR1aW5vIFdpcmUgaW5jbHVkZ"& _ 
            "ToKI2luY2x1ZGUgPFdpcmUuaD4gICAgICAgICAgICAgICAvLyBPbmx5IG5lZWRlZCBmb3IgQXJkdWlub"& _ 
            "yAxLjYuNSBhbmQgZWFybGllcgojaW5jbHVkZSAiU1NEMTMwNldpcmUuaCIgICAgICAgIC8vIGxlZ2Fje"& _ 
            "TogI2luY2x1ZGUgIlNTRDEzMDYuaCIKI2luY2x1ZGUgImltYWdlcy5oIgovLy0tLS0tLS0tLS0tLS0tL"& _ 
            "S0tLS0tLS0tLS0tLS0tLQovLyBJbml0aWFsaXplIHRoZSBPTEVEIGRpc3BsYXkgdXNpbmcgQXJkdWlub"& _ 
            "yBXaXJlOgpTU0QxMzA2V2lyZSBkaXNwbGF5KDB4M2MsIFNEQSwgU0NMKTsgIAovLy0tLS0tLS0tLS0tL"& _ 
            "S0tLS0tLS0tLS0tLS0tLS0tLQpmbG9hdCBWZXJzaW9uID0gMS4zOwovLy0tLS0tLS0tLS0tLS0tLS0tL"& _ 
            "S0tLS0tLS0tLS0tLQpTdHJpbmcgc3NpZF9zZXR1cCAgICAgPSAiJVNTSUQlIjsKU3RyaW5nIHBhc3N3b"& _ 
            "3JkX3NldHVwID0gIiVTU0lEUEFTU1dPUkQlIjsKU3RyaW5nIHNlY3JldGtleSAgICAgID0gIiVTRUNSR"& _ 
            "VRLRVklIjsKU3RyaW5nIGJhY2tlbmQgICAgICAgID0gImh0dHA6Ly8lQkFDS0VORCU6ODA4MCI7ClN0c"& _ 
            "mluZyBlc3BuYW1lICAgICAgICA9ICIlRVNQTkFNRSUiOwovLy0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tL"& _ 
            "S0tLS0tLQojZGVmaW5lIERIVFRZUEUgREhUMTEKLy8gREhUIFNlbnNvcgp1aW50OF90IERIVFBpbiA9I"& _ 
            "DEyOyAvLzE0IGJldm9yIEzDtnR0ZXN0CkpTT05WYXIgZGF0YTsKZmxvYXQgZGh0SHVtaWRpdHkgPSAwO"& _ 
            "wpmbG9hdCBkaHRUZW1wZXJhdHVyZSA9IDA7ICAgClN0cmluZyBsb2NhbGlwOyAgICAgICAgICAgCi8vI"& _ 
            "EluaXRpYWxpemUgREhUIHNlbnNvci4KREhUIGRodChESFRQaW4sIERIVFRZUEUpOyAgIAppbnQgbmV0d"& _ 
            "29yazsKU3RyaW5nIG1lc3NhZ2UgPSAiIjsKZmxvYXQgdGVtcDsKZmxvYXQgaHVtaWQ7CkR5bmFtaWNKc"& _ 
            "29uRG9jdW1lbnQgZGF0YXNlbmQoMTAyNCk7Cgp2b2lkIHNldHVwKCkgewogIFNlcmlhbC5iZWdpbigxM"& _ 
            "TUyMDApOwogIGRpc3BsYXkuaW5pdCgpOwogIHBpbk1vZGUoREhUUGluLCBJTlBVVCk7CiAgZGh0LmJlZ"& _ 
            "2luKCk7CiAgZGlzcGxheS5jbGVhcjsKICBkaXNwbGF5LnNldEZvbnQoQXJpYWxNVF9QbGFpbl8xNik7C"& _ 
            "iAgZGlzcGxheS5kcmF3U3RyaW5nKDAsIDEwLCAiQ29ubmVjdGluZyB0byBXaUZpIik7CiAgZGlzcGxhe"& _ 
            "S5kaXNwbGF5KCk7CiAgV2lGaS5iZWdpbihzc2lkX3NldHVwLCBwYXNzd29yZF9zZXR1cCk7ICAgICAgI"& _ 
            "CAgICAgIC8vIENvbm5lY3QgdG8gdGhlIG5ldHdvcmsKICBTZXJpYWwucHJpbnQoIkNvbm5lY3Rpbmcgd"& _ 
            "G8gIik7CiAgU2VyaWFsLnByaW50KHNzaWRfc2V0dXApOyBTZXJpYWwucHJpbnRsbigiIC4uLiIpOwogI"& _ 
            "AogIGludCBpID0gMDsKICB3aGlsZSAoV2lGaS5zdGF0dXMoKSAhPSBXTF9DT05ORUNURUQpIHsgLy8gV"& _ 
            "2FpdCBmb3IgdGhlIFdpLUZpIHRvIGNvbm5lY3QKICAgIGRlbGF5KDEwMDApOwogICAgU2VyaWFsLnBya"& _ 
            "W50KCsraSk7IFNlcmlhbC5wcmludCgnICcpOwogIH0KICAKICBTZXJpYWwucHJpbnRsbignXG4nKTsKI"& _ 
            "CBTZXJpYWwucHJpbnRsbigiQ29ubmVjdGlvbiBlc3RhYmxpc2hlZCEiKTsgIAogIFNlcmlhbC5wcmlud"& _ 
            "CgiSVAgYWRkcmVzczpcdCIpOwogIFNlcmlhbC5wcmludGxuKFdpRmkubG9jYWxJUCgpKTsKICAKICAKI"& _ 
            "CBTZXJpYWwucHJpbnQoIiMjIyNSZWdpc3RlciBEZXZpY2UjIyMjIyIpOyAgCiAgZGF0YXNlbmRbIm5hb"& _ 
            "WUiXSA9IGVzcG5hbWU7CiAgZGF0YXNlbmRbInNlY3JldGtleSJdID0gc2VjcmV0a2V5OwogIGRhdGFzZ"& _ 
            "W5kWyJ0ZW1wZXJhdHVyZSJdID0gdGVtcDsKICBkYXRhc2VuZFsiaHVtaWRpdHkiXSA9IGh1bWlkOwogI"& _ 
            "GRhdGFzZW5kWyJ2ZXJzaW9uIl0gPSAiMS4zIjsKICBkYXRhc2VuZFsidHlwZSJdID0gIlRoZXJtb3N0Y"& _ 
            "XQiOwogIGRhdGFzZW5kWyJpcGFkZHJlc3MiXSA9IFdpRmkubG9jYWxJUCgpLnRvU3RyaW5nKCk7CiAgU"& _ 
            "2VyaWFsLnByaW50bG4oIk5hbWU6ICIgKyBlc3BuYW1lKTsKICBTZXJpYWwucHJpbnRsbigiU2VjcmV0a"& _ 
            "2V5OiAiICsgU3RyaW5nKGRhdGFzZW5kWyJzZWNyZXRrZXkiXSkpOwogIFNlcmlhbC5wcmludGxuKCJWZ"& _ 
            "XJzaW9uOiAiICsgU3RyaW5nKGRhdGFzZW5kWyJ2ZXJzaW9uIl0pKTsKICBTZXJpYWwucHJpbnRsbigiS"& _ 
            "VBBZGRyZXNzOiAiICsgU3RyaW5nKGRhdGFzZW5kWyJpcGFkZHJlc3MiXSkpOwogIFNlcmlhbC5wcmlud"& _ 
            "GxuKCJUZW1wOiAiICsgU3RyaW5nKHRlbXApICsgIiBIdW1pZGl0eTogIiArIFN0cmluZyhodW1pZCkpO"& _ 
            "wogIFN0cmluZyBkYXRhc2VuZHg7CiAgc2VyaWFsaXplSnNvbihkYXRhc2VuZCwgZGF0YXNlbmR4KTsKI"& _ 
            "CAKICBTZXJpYWwucHJpbnQoIiMjIyMjIyMjIyMjIyMjIyMjIyMjIyMjIyMjIyMjIyIpOyAgCiAgV2lGa"& _ 
            "UNsaWVudCBjbGllbnQ7CiAgSFRUUENsaWVudCBodHRwOwogIGh0dHAuYmVnaW4oY2xpZW50LCBiYWNrZ"& _ 
            "W5kICsgIi9jbGllbnQvcmVnaXN0ZXIvIik7CiAgaHR0cC5hZGRIZWFkZXIoIkNvbnRlbnQtVHlwZSIsI"& _ 
            "CJhcHBsaWNhdGlvbi9qc29uIik7CiAgaW50IGh0dHBQb3N0UmVzcG9uc2UgPSBodHRwLlBPU1QoZGF0Y"& _ 
            "XNlbmR4KTsgIAogIGh0dHAuZW5kKCk7CgogIHVwZGF0ZURhdGEoKTsKfQoKdm9pZCBsb29wKCkgewogI"& _ 
            "Ap9Cgp2b2lkIHVwZGF0ZURhdGEoKXsgICAgIAogIHdoaWxlICh0cnVlKSB7CiAgICBmb3IgKGludCBpI"& _ 
            "D0gMDsgaSA8PSAxMDsgaSsrKSB7CiAgICAgIGRodEh1bWlkaXR5ID0gZGh0LnJlYWRIdW1pZGl0eSgpO"& _ 
            "wogICAgICBkaHRUZW1wZXJhdHVyZSA9IGRodC5yZWFkVGVtcGVyYXR1cmUoKTsKICAgICAgZGVsYXkoM"& _ 
            "TAwKTsKICAgICAgdGVtcCA9IGRodFRlbXBlcmF0dXJlOwogICAgICBodW1pZCA9IGRodEh1bWlkaXR5O"& _ 
            "wogICAgfQogICAgCgogICAgZGF0YXNlbmRbIm5hbWUiXSA9IGVzcG5hbWU7CiAgICBkYXRhc2VuZFsic"& _ 
            "2VjcmV0a2V5Il0gPSBzZWNyZXRrZXk7CiAgICBkYXRhc2VuZFsidGVtcGVyYXR1cmUiXSA9IHRlbXA7C"& _ 
            "iAgICBkYXRhc2VuZFsiaHVtaWRpdHkiXSA9IGh1bWlkOwogICAgZGF0YXNlbmRbInZlcnNpb24iXSA9I"& _ 
            "CIxLjMiOwogICAgZGF0YXNlbmRbInR5cGUiXSA9ICJUaGVybW9zdGF0IjsKICAgIGRhdGFzZW5kWyJpc"& _ 
            "GFkZHJlc3MiXSA9IFdpRmkubG9jYWxJUCgpLnRvU3RyaW5nKCk7CiAgICBTZXJpYWwucHJpbnQoIiMjI"& _ 
            "yNVUERBVEUgREVWSUNFIyMjIyMiKTsgIAogICAgU2VyaWFsLnByaW50bG4oIk5hbWU6ICIgKyBlc3BuY"& _ 
            "W1lKTsKICAgIFNlcmlhbC5wcmludGxuKCJTZWNyZXRrZXk6ICIgKyBTdHJpbmcoZGF0YXNlbmRbInNlY"& _ 
            "3JldGtleSJdKSk7CiAgICBTZXJpYWwucHJpbnRsbigiVmVyc2lvbjogIiArIFN0cmluZyhkYXRhc2VuZ"& _ 
            "FsidmVyc2lvbiJdKSk7CiAgICBTZXJpYWwucHJpbnRsbigiSVBBZGRyZXNzOiAiICsgU3RyaW5nKGRhd"& _ 
            "GFzZW5kWyJpcGFkZHJlc3MiXSkpOwogICAgU2VyaWFsLnByaW50bG4oIlRlbXA6ICIgKyBTdHJpbmcod"& _ 
            "GVtcCkgKyAiIEh1bWlkaXR5OiAiICsgU3RyaW5nKGh1bWlkKSk7CiAgICBsb2NhbGlwID0gV2lGaS5sb"& _ 
            "2NhbElQKCkudG9TdHJpbmcoKTsKICAgIFNlcmlhbC5wcmludGxuKCJMb2NhbCBJUCBmcm9tIFZBUjogI"& _ 
            "iArIGxvY2FsaXApOwoKICAgIFN0cmluZyBkYXRhc2VuZHg7CiAgICBzZXJpYWxpemVKc29uKGRhdGFzZ"& _ 
            "W5kLCBkYXRhc2VuZHgpOwogICAgLy9TZXJpYWwucHJpbnRsbigiU2VuZGluZyBEYXRhOiAiICsgSlNPT"& _ 
            "i5zdHJpbmdpZnkoZGF0YSkgKyAiIHRvIC0+ICIgKyBkYXRheFsiYmFja2VuZCJdICsgIi9jbGllbnQvc"& _ 
            "mVnaXN0ZXIvIik7CiAgICBkaXNwbGF5LmNsZWFyKCk7CiAgICBkaXNwbGF5LmRyYXdTdHJpbmdNYXhXa"& _ 
            "WR0aCgwLCAwLCAxMjgsCiAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIlRlbXBlcmF0dXJlOiAiI"& _ 
            "CsgdGVtcCArICIgQ8KwXG4gSHVtaWRpdHk6ICIgKyBodW1pZCArICIgJSIgKTsKICAgIGRpc3BsYXkuZ"& _ 
            "GlzcGxheSgpOwogICAgU2VyaWFsLnByaW50KCJVcGRhdGluZyBEYXRhc2V0Olx0Iik7ICAKICAgIFdpR"& _ 
            "mlDbGllbnQgY2xpZW50OwogICAgSFRUUENsaWVudCBodHRwOwogICAgaHR0cC5iZWdpbihjbGllbnQsI"& _ 
            "GJhY2tlbmQgKyAiL2NsaWVudC91cGRhdGUvIik7CiAgICBodHRwLmFkZEhlYWRlcigiQ29udGVudC1Ue"& _ 
            "XBlIiwgImFwcGxpY2F0aW9uL2pzb24iKTsKICAgIGludCBodHRwUG9zdFJlc3BvbnNlID0gaHR0cC5QT"& _ 
            "1NUKGRhdGFzZW5keCk7ICAKICAgIGh0dHAuZW5kKCk7CiAgICBTZXJpYWwucHJpbnRsbigpOwogICAgZ"& _ 
            "GVsYXkoNjAwMDApOyAvLzNlOCBmw7xyIDVtaW4KICB9Cn0=")>  _
        Public Property srcThermy() As String
            Get
                Return CType(Me("srcThermy"),String)
            End Get
            Set
                Me("srcThermy") = value
            End Set
        End Property
    End Class
End Namespace

Namespace My
    
    <Global.Microsoft.VisualBasic.HideModuleNameAttribute(),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute()>  _
    Friend Module MySettingsProperty
        
        <Global.System.ComponentModel.Design.HelpKeywordAttribute("My.Settings")>  _
        Friend ReadOnly Property Settings() As Global.EioT_Flasher.My.MySettings
            Get
                Return Global.EioT_Flasher.My.MySettings.Default
            End Get
        End Property
    End Module
End Namespace
